const REQUEST = 'REQUEST';
const REQUEST_FAILURE = 'REQUEST_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export {
  REQUEST, LOGIN_SUCCESS, REQUEST_FAILURE, LOGOUT_SUCCESS,
};
