const REQUEST = 'REQUEST';
const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
const REQUEST_FAILURE = 'REQUEST_FAILURE';
const CLEAN_ERROR = 'CLEAN_ERROR';
const CLEAN_NOTICE = 'CLEAN_NOTICE';
const NOTIFY = 'NOTIFY';

export {
  REQUEST, REQUEST_SUCCESS, REQUEST_FAILURE, CLEAN_ERROR, CLEAN_NOTICE, NOTIFY,
};
